// Database query functions for the webhooks module.
// All functions use serverClient() (service role, bypasses RLS).
// Call only from server-side code — API routes, server actions, delivery utility.

import { serverClient } from '@/lib/db/supabase';
import type { WebhookEndpoint, WebhookDelivery, WebhookDeliveryStatus, WebhookEventType, WebhookEventPayload } from '@/lib/types/webhooks';
import type { WebhookEndpointInput } from '@/lib/validations/webhooks';

// ---------------------------------------------------------------------------
// Row types (mirror DB columns)
// ---------------------------------------------------------------------------

interface EndpointRow {
  id:          string;
  url:         string;
  description: string | null;
  secret:      string;
  events:      string[];
  is_active:   boolean;
  created_at:  string;
  updated_at:  string;
}

interface DeliveryRow {
  id:             string;
  endpoint_id:    string;
  event_type:     string;
  payload:        Record<string, unknown>;
  status:         string;
  http_status:    number | null;
  response_body:  string | null;
  attempt_number: number;
  attempted_at:   string;
}

// ---------------------------------------------------------------------------
// Mapping helpers
// ---------------------------------------------------------------------------

function endpointFromRow(row: EndpointRow): WebhookEndpoint {
  return {
    id:          row.id,
    url:         row.url,
    description: row.description ?? undefined,
    secret:      row.secret,
    events:      row.events as WebhookEventType[],
    isActive:    row.is_active,
    createdAt:   row.created_at,
    updatedAt:   row.updated_at,
  };
}

function deliveryFromRow(row: DeliveryRow): WebhookDelivery {
  return {
    id:            row.id,
    endpointId:    row.endpoint_id,
    eventType:     row.event_type as WebhookEventType,
    payload:       row.payload,
    status:        row.status as WebhookDeliveryStatus,
    httpStatus:    row.http_status ?? undefined,
    responseBody:  row.response_body ?? undefined,
    attemptNumber: row.attempt_number,
    attemptedAt:   row.attempted_at,
  };
}

// ---------------------------------------------------------------------------
// Endpoint queries
// ---------------------------------------------------------------------------

/** Returns all webhook endpoints, ordered by creation date descending. */
export async function listWebhookEndpoints(): Promise<{ data: WebhookEndpoint[] | null; error: string | null }> {
  try {
    const { data, error } = await serverClient()
      .from('webhook_endpoints')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) return { data: null, error: error.message };
    return { data: (data as EndpointRow[]).map(endpointFromRow), error: null };
  } catch (err) {
    console.error('[listWebhookEndpoints]', err);
    return { data: null, error: 'Failed to load webhook endpoints' };
  }
}

/** Returns all active endpoints subscribed to a given event type. Used by the delivery utility. */
export async function listActiveEndpointsForEvent(
  eventType: WebhookEventType,
): Promise<{ data: WebhookEndpoint[] | null; error: string | null }> {
  try {
    const { data, error } = await serverClient()
      .from('webhook_endpoints')
      .select('*')
      .eq('is_active', true)
      .contains('events', [eventType]);

    if (error) return { data: null, error: error.message };
    return { data: (data as EndpointRow[]).map(endpointFromRow), error: null };
  } catch (err) {
    console.error('[listActiveEndpointsForEvent]', err);
    return { data: null, error: 'Failed to load endpoints for event' };
  }
}

/** Creates a webhook endpoint. The secret must be generated by the caller before calling this. */
export async function createWebhookEndpoint(
  input: WebhookEndpointInput,
  secret: string,
): Promise<{ data: WebhookEndpoint | null; error: string | null }> {
  try {
    const { data, error } = await serverClient()
      .from('webhook_endpoints')
      .insert({
        url:         input.url,
        description: input.description || null,
        secret,
        events:      input.events,
        is_active:   true,
      })
      .select('*')
      .single();

    if (error) return { data: null, error: error.message };
    return { data: endpointFromRow(data as EndpointRow), error: null };
  } catch (err) {
    console.error('[createWebhookEndpoint]', err);
    return { data: null, error: 'Failed to create webhook endpoint' };
  }
}

/** Deletes a webhook endpoint. Deliveries are cascade-deleted by the DB. */
export async function deleteWebhookEndpoint(id: string): Promise<{ error: string | null }> {
  try {
    const { error } = await serverClient()
      .from('webhook_endpoints')
      .delete()
      .eq('id', id);

    if (error) return { error: error.message };
    return { error: null };
  } catch (err) {
    console.error('[deleteWebhookEndpoint]', err);
    return { error: 'Failed to delete webhook endpoint' };
  }
}

// ---------------------------------------------------------------------------
// Delivery queries
// ---------------------------------------------------------------------------

/** Returns the last 50 delivery attempts for a given endpoint, newest first. */
export async function listWebhookDeliveries(
  endpointId: string,
): Promise<{ data: WebhookDelivery[] | null; error: string | null }> {
  try {
    const { data, error } = await serverClient()
      .from('webhook_deliveries')
      .select('*')
      .eq('endpoint_id', endpointId)
      .order('attempted_at', { ascending: false })
      .limit(50);

    if (error) return { data: null, error: error.message };
    return { data: (data as DeliveryRow[]).map(deliveryFromRow), error: null };
  } catch (err) {
    console.error('[listWebhookDeliveries]', err);
    return { data: null, error: 'Failed to load webhook deliveries' };
  }
}

/** Inserts a delivery record and returns its id. Used by the delivery utility. */
export async function createWebhookDelivery(
  endpointId:    string,
  eventType:     WebhookEventType,
  payload:       WebhookEventPayload,
  status:        WebhookDeliveryStatus,
  httpStatus:    number | null,
  responseBody:  string | null,
): Promise<{ id: string | null; error: string | null }> {
  try {
    const { data, error } = await serverClient()
      .from('webhook_deliveries')
      .insert({
        endpoint_id:   endpointId,
        event_type:    eventType,
        payload:       payload as unknown as Record<string, unknown>,
        status,
        http_status:   httpStatus,
        response_body: responseBody,
        attempt_number: 1,
      })
      .select('id')
      .single();

    if (error) return { id: null, error: error.message };
    return { id: (data as { id: string }).id, error: null };
  } catch (err) {
    console.error('[createWebhookDelivery]', err);
    return { id: null, error: 'Failed to log webhook delivery' };
  }
}
